name: Rewards App CI

on:
  push:
    branches:
      - main
      - feature/rewards-app-implementation

  pull_request:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install Dependencies
        run: npm ci


      - name: Run Lint
        run: npm run lint


      - name: Run Tests
        run: npm test


      - name: Coverage
        run: npm run test:coverage


      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'

        uses: peaceiris/actions-gh-pages@v4

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./dist